package com.braingrow.service;
import com.braingrow.dto.*; import com.braingrow.entity.*; import com.braingrow.repository.*; import com.braingrow.security.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom; import java.time.LocalDateTime;
@Service public class AuthService {
 private final UserRepository users; private final VerificationCodeRepository codes; private final PasswordEncoder encoder; private final JwtService jwt; private final EmailService email; private final LoginAttemptService attempts; private final SecureRandom random=new SecureRandom(); private final int codeMinutes, cooldown;
 public AuthService(UserRepository u,VerificationCodeRepository c,PasswordEncoder e,JwtService j,EmailService m,LoginAttemptService a,@Value("${app.verification-expiration-minutes:10}") int cm,@Value("${app.verification-cooldown-seconds:60}") int cd){users=u;codes=c;encoder=e;jwt=j;email=m;attempts=a;codeMinutes=cm;cooldown=cd;}
 @Transactional public void register(RegisterRequest r){String em=norm(r.email());if(users.existsByEmailIgnoreCase(em))throw new IllegalArgumentException("Email already registered");User u=new User();u.setEmail(em);u.setPasswordHash(encoder.encode(r.password()));u.setAge(r.age());u.setRole(Role.STUDENT);u.setEnabled(true);users.save(u);}
 public AuthResponse login(LoginRequest r){String em=norm(r.email());if(attempts.isLocked(em))throw new IllegalArgumentException("Too many failed attempts. Try again later.");User u=users.findByEmailIgnoreCase(em).orElse(null);if(u==null||!u.isEnabled()||!encoder.matches(r.password(),u.getPasswordHash())){attempts.failure(em);throw new IllegalArgumentException("Invalid email or password");}attempts.success(em);return new AuthResponse(jwt.generate(u.getEmail(),u.getRole().name()),u.getEmail(),u.getRole().name());}
 @Transactional public void sendResetCode(String emailAddress){String em=norm(emailAddress);var user=users.findByEmailIgnoreCase(em);if(user.isEmpty())throw new IllegalArgumentException("If the account exists, a code will be sent");var last=codes.findTopByEmailIgnoreCaseAndPurposeOrderByExpiresAtDesc(em,"RESET");if(last.isPresent()&&last.get().getExpiresAt().minusMinutes(codeMinutes).plusSeconds(cooldown).isAfter(LocalDateTime.now()))throw new IllegalArgumentException("Please wait before requesting another code");codes.deleteByEmailIgnoreCaseAndPurpose(em,"RESET");VerificationCode v=new VerificationCode();v.setEmail(em);v.setPurpose("RESET");v.setCode(String.format("%06d",random.nextInt(1_000_000)));v.setExpiresAt(LocalDateTime.now().plusMinutes(codeMinutes));codes.save(v);email.sendCode(em,v.getCode());}
 @Transactional public void reset(ResetPasswordRequest r){String em=norm(r.email());VerificationCode v=codes.findTopByEmailIgnoreCaseAndPurposeOrderByExpiresAtDesc(em,"RESET").orElseThrow(()->new IllegalArgumentException("Invalid or expired code"));if(v.getExpiresAt().isBefore(LocalDateTime.now())||!v.getCode().equals(r.code()))throw new IllegalArgumentException("Invalid or expired code");User u=users.findByEmailIgnoreCase(em).orElseThrow(()->new IllegalArgumentException("Invalid or expired code"));u.setPasswordHash(encoder.encode(r.newPassword()));users.save(u);codes.delete(v);attempts.success(em);}
 private String norm(String s){return s.trim().toLowerCase(Locale.ROOT);}
}
